# General Jekyll Config
pygments: true
url: http://openvnet.com
lsi: false
exclude: [LICENSE, CNAME, README.md, Rakefile, .gitignore]

# Pagenation
pagenate: 5
paginate_path: "post/page:num"

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: axsh
    twitter: WakameTech
    # hacker_news: swanson

  # "Hi, I'm _______"
  name: OpenVNet
  email: contact@axsh.net
  tagline: "IaaS, virtual data center, virtual machine, virtual server, virtual network, virtual storage"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-814567-9

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
